//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UngDungQuanLy
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoDich
    {
        public int Id { get; set; }
        public Nullable<int> SoHoaDon { get; set; }
        public Nullable<System.DateTime> NgayGiaoDich { get; set; }
        public string TenKhachHang { get; set; }
        public string DiaChi { get; set; }
        public string Sdt { get; set; }
        public Nullable<int> MaHangHoa { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> Giam { get; set; }
        public Nullable<int> ThanhTien { get; set; }
        public string TenHangHoa { get; set; }
    }
}
