//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UngDungQuanLy
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangHoa
    {
        public int Id { get; set; }
        public string Loai { get; set; }
        public string Ten { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> GiaNiemYet { get; set; }
        public Nullable<int> GiaBanLe { get; set; }
        public Nullable<int> GiaThucTe { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public byte[] HinhAnh { get; set; }
    }
}
