//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UngDungQuanLy
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiHangHoa
    {
        public int Id { get; set; }
        public string TenLoai { get; set; }
    }
}
